language: cpp

<<<<<<< HEAD
dist: trusty
=======
dist: xenial 

before_install:
  - PY_CMD=python3
>>>>>>> alex-new-master

script:
  - mkdir -p build 
  - cd build
  - cmake .. -DRUN_UNIT_TEST=ON -DPYTHON_EXECUTABLE=$(which $PY_CMD) 
  - cmake --build . -j 2

matrix:
  include:
    - compiler: gcc
    - compiler: clang 

matrix:
  include:
    - compiler: gcc
    - compiler: clang 

notifications:
  email:
    on_success: change
    on_failure: always
